src/components/Home/Cryptocurrencies/Cryptocurrencies.js, src/components/Home/Statistics/Statistics.js, src/components/Home/TraditionalDomains/TraditionalDomains.js
Corrected "Registered Names" number after Makoto fixed Dune, extended cryptocurrency logos going into wallet to extend past the width of the page, some copy updates
=> Some updates on details

locales/de/translation.json, src/components/Home/Ecosystem/Ecosystem.js
Adding the German localization for the new version of your landing page. Let me know if you want anything changed or shortened (because of layout issues or something like that).
=> Add German localization

src/components/Home/Ecosystem/Ecosystem.js, src/components/Home/Statistics/Statistics.js
Reverts ensdomains/ensdomains-v2#94
=> Revert "Fix problem and update stats"

src/components/Home/Ecosystem/Ecosystem.js
Reverts ensdomains/ensdomains-v2#92
=> Revert "Update Ecosystem.js"

src/components/Home/Ecosystem/Ecosystem.js, src/components/Home/Statistics/Statistics.js
Reverts ensdomains/ensdomains-v2#91
=> Revert "Switch see more and see less on homepage"

gatsby-config.js, locales/it/translation.json, src/components/LanguageSwitcher.js
Added IT translation even to align the website translation with app.ens.
=> Italian translation

gatsby-config.js, locales/cn/translation.json, locales/de/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/it/translation.json, locales/ja/translation.json, locales/ko/translation.json, locales/nl/translation.json, locales/pl/translation.json, locales/ru/translation.json, locales/vi/translation.json
=> add missing keys

src/components/Navigationv2.js
fixes scrollbar issue #345 
also the team link now links to /about instead of being blank
=> small navigationv2 visual fixes

locales/it/translation.json
I have fixed some of my original strings in Italian.
=> Fix some Italian translations

src/components/Home/PortableUsername/PortableUsername.js
=> fix: center align brantly.eth

locales/pt/translation.json, src/components/LanguageSwitcher.js, src/components/LanguageSwitcherv2.js
Add the portuguese translation to v2
=> Add portuguese translations

src/components/About/AboutENS/AboutENS.js, src/components/About/Team/Team.js, src/components/Anchor.js, src/components/DAOBanner.js, src/components/GetInvolved.js, src/components/Home/AdditionalFeatures/AdditionalFeatures.js, src/components/Home/Carousel/Carousel.js, src/components/Home/Cryptocurrencies/Cryptocurrencies.js, src/components/Home/DecentralisedWebsites/DecentralisedWebsites.js, src/components/Home/Hero.js, src/components/Home/PortableUsername/PortableUsername.js, src/components/Home/Statistics/Statistics.js, src/components/Home/TraditionalDomains/TraditionalDomains.js, src/components/Icons/SmallCaret.js, src/components/LanguageSwitcher.js, src/components/LanguageSwitcherv2.js, src/components/Layout.js, src/components/Navigationv2.js, src/components/Typography.js, src/pages/governance.js, src/utils.js
- Removed unused vars and imports
- Fix lint warnings
- Format the codebase using `npm run format` with prettier
cc @brantlymillegan @LeonmanRolls @jefflau
=> chore: format codebase

src/components/Home/Ecosystem/Ecosystem.js
=> chore: center align ecosystem titles to center with icon

src/components/Home/Ecosystem/Ecosystem.js
Improve a11y a bit
https://user-images.githubusercontent.com/69431456/148332788-3629e309-bfe0-44a8-9738-63010f5ed419.mov
cc @brantlymillegan @LeonmanRolls @jefflau
=> feat: add hover effect color for app titles

src/components/DAOBanner.js
Make the eligibility date more explicit
=> Update banner message

src/components/Home/Statistics/Statistics.js
=> chore: update stats

src/components/Home/links.json
=> Fix spelling error

locales/en/translation.json, src/components/DAOBanner.js
https://user-images.githubusercontent.com/1221141/192455047-914da03c-5920-4705-8b4d-74e62251f7c2.mov
=> Switch DAOBanner to swag

locales/en/translation.json, src/components/DAOBanner.js
Switched back the swag banner to the constitution one.
=> changed swag banner for constitution

locales/de/translation.json
Added missing locales to the language file and translated them into German
=> Update German translations & add missing locales

src/components/Home/links.json
Replace references to `.eth.link` with `.eth.limo` for apps.
=> Remove references to eth.link

src/components/Layout.js
This is to add an aggregated view across different sites https://plausible.io/docs/plausible-script#is-there-a-roll-up-view
=> Add rollup.ens

src/components/Home/links.json
https://atticc.xyz/home
Check via link above
Atticc is a Web3 social app integrated with ENS
1. supports searching users by ENS
2. supports using ENS as user ID
3. prioritizes content from users with ENS
=> integrations: add atticc.json

locales/nl/translation.json
=> Update Dutch translation file

gatsby-config.js, locales/tr/translation.json, src/components/LanguageSwitcher.js, src/components/LanguageSwitcherv2.js
* Add new tr folder
* Add new tr translation.json file
* Add tr to languages in config file
* Add turkish to language switch component
=> Add Turkish language support

src/components/Layout.js
relative import didn't work, so just using a URL instead
=> fix og image link

_redirects, public/_redirects, src/components/Navbar/Navbar.tsx
=> Add redirects

src/components/SearchInput/SearchInput.tsx
Tracking the search form button by following https://plausible.io/docs/custom-event-goals
=> Add plausible-event-name

public/_headers
This reverts commit 4f97302a368961f0b8dc092ebb7b50ea35fcf14d.
=> Revert "Basic CSP (#666)"
